language: python
python:
    - "3.6"
install:
    - pip install -q -r requirements.txt
# Continuação do Script
script:
# - script para executar os testes da aplicação, por exemplo: python tests.py ou
    - pytest
